name: IRC Notify

on: push

jobs:

  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        uses: Gottox/irc-message-action@v2
        if: github.event_name == 'push'
        with:
          channel: '#zeppe-lin'
          nickname: zeppe-lin
          sasl_password: ${{ secrets.LIBERACHAT_PASSWORD }}
          message: |-
            ${{ github.actor }} pushed ${{ github.event.repository.name }}:${{ github.ref_name || github.event.ref }} -- ${{ github.event.compare }}
            ${{ join(github.event.commits.*.message, '
            ') }}

# End of file.
